version: '2'
jobs:
  build:
    working_directory: /go/src/github.com/qri-io/qri
    docker:
      - image: circleci/golang:1.11.1
        environment:
          GOLANG_ENV: test
          PORT: 3000
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report golang.org/x/lint/golint github.com/jinzhu/copier
      - run:
          name: Run Lint Tests
          command: golint -set_exit_status ./...
      - run:
          name: Install non-gx deps
          command: make install-deps
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install gx
          command: >
            go get
            github.com/whyrusleeping/gx
            github.com/whyrusleeping/gx-go
      - run:
          name: Install gx deps
          command: >
            gx install
      - run:
          name: Install gx-dependant packages
          command: >
            make install-gx-dep-packages
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - /go/src/gx/
      - run:
          name: Run Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            ./.circleci/cover.test.sh | tee ${TEST_RESULTS}/go-test.out
      - run:
          name: Publish coverage info to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
